<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MangasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mangas')->insert([
            [
                'id' => 1,
                'serie_fk' => 1,
                'title' => 'Boku no Hero Academia 01',
                'en_alternative_title' => 'My Hero Academia 01',
                'es_alternative_title' => 'Mi Academia de Heroes 01',
                'synopsis' => 'Las personas no nacen igual. El protagonista de esta historia es uno de esos casos raros que nacen sin superpoderes, pero esto no le impedirá perseguir su sueño: ser un gran héroe como el legendario All-Might. Para convertirse en el héroe que quiere ser, se apuntará a una de las academias de héroes más prestigiosas del país: Yueiko. Con la ayuda de su ídolo, All-Might, ¿podrá convertirse en un verdadero héroe?',
                'price' => 105000,
                'release_date' => '2001-12-21',
                'cover' => 'myHeroAcademia01.jpg',
                'cover_description' => "Tapa del volumen 1 de My Hero Academia",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'serie_fk' => 1,
                'title' => 'Boku no Hero Academia 02',
                'en_alternative_title' => 'My Hero Academia 02',
                'es_alternative_title' => 'Mi Academia de Heroes 02',
                'synopsis' => 'Las personas no nacen igual. El protagonista de esta historia es uno de esos casos raros que nacen sin superpoderes, pero esto no le impedirá perseguir su sueño: ser un gran héroe como el legendario All-Might. Para convertirse en el héroe que quiere ser, se apuntará a una de las academias de héroes más prestigiosas del país: Yueiko. Con la ayuda de su ídolo, All-Might, ¿podrá convertirse en un verdadero héroe?',
                'price' => 105000,
                'release_date' => '2001-12-21',
                'cover' => 'myHeroAcademia02.jpg',
                'cover_description' => "Tapa del volumen 2 de My Hero Academia",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'serie_fk' => 1,
                'title' => 'Boku no Hero Academia 03',
                'en_alternative_title' => 'My Hero Academia 03',
                'es_alternative_title' => 'Mi Academia de Heroes 03',
                'synopsis' => 'Las personas no nacen igual. El protagonista de esta historia es uno de esos casos raros que nacen sin superpoderes, pero esto no le impedirá perseguir su sueño: ser un gran héroe como el legendario All-Might. Para convertirse en el héroe que quiere ser, se apuntará a una de las academias de héroes más prestigiosas del país: Yueiko. Con la ayuda de su ídolo, All-Might, ¿podrá convertirse en un verdadero héroe?',
                'price' => 105000,
                'release_date' => '2001-12-21',
                'cover' => 'myHeroAcademia03.jpg',
                'cover_description' => "Tapa del volumen 3 de My Hero Academia",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'serie_fk' => 1,
                'title' => 'Boku no Hero Academia 04',
                'en_alternative_title' => 'My Hero Academia 04',
                'es_alternative_title' => 'Mi Academia de Heroes 04',
                'synopsis' => 'Las personas no nacen igual. El protagonista de esta historia es uno de esos casos raros que nacen sin superpoderes, pero esto no le impedirá perseguir su sueño: ser un gran héroe como el legendario All-Might. Para convertirse en el héroe que quiere ser, se apuntará a una de las academias de héroes más prestigiosas del país: Yueiko. Con la ayuda de su ídolo, All-Might, ¿podrá convertirse en un verdadero héroe?',
                'price' => 105000,
                'release_date' => '2001-12-21',
                'cover' => 'myHeroAcademia04.jpg',
                'cover_description' => "Tapa del volumen 4 de My Hero Academia",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'serie_fk' => 2,
                'title' => 'Gotoubun no Hanayome 01',
                'en_alternative_title' => 'The Quintessential Quintuplets 01',
                'es_alternative_title' => 'Somos Quintillizas 01',
                'synopsis' => 'Fuutarou Uesugi es un estudiante de segundo año de preparatoria/instituto cuya familia siempre ha sido muy pobre. Un día recibe una suculenta oferta de trabajo como tutor a medio tiempo... ¡pero sus estudiantes resultan ser unas chicas de su propia clase! Para complicar más las cosas, son quintillizas... Las cinco hermanas son todas muy atractivas, pero no es lo único que tienen en común: todas odian estudiar y sus calificaciones siempre están al límite de la catástrofe. Tendrá que conseguir que las cinco estudien, pero primero tendrá que estudiar él cómo ganarse su confianza.',
                'price' => 100000,
                'release_date' => '2001-12-21',
                'cover' => 'somosQuintillizas01.jpg',
                'cover_description' => "Tapa del volumen 1 de Somos Quintillizas",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'serie_fk' => 2,
                'title' => 'Gotoubun no Hanayome 02',
                'en_alternative_title' => 'The Quintessential Quintuplets 02',
                'es_alternative_title' => 'Somos Quintillizas 02',
                'synopsis' => 'Fuutarou Uesugi es un estudiante de segundo año de preparatoria/instituto cuya familia siempre ha sido muy pobre. Un día recibe una suculenta oferta de trabajo como tutor a medio tiempo... ¡pero sus estudiantes resultan ser unas chicas de su propia clase! Para complicar más las cosas, son quintillizas... Las cinco hermanas son todas muy atractivas, pero no es lo único que tienen en común: todas odian estudiar y sus calificaciones siempre están al límite de la catástrofe. Tendrá que conseguir que las cinco estudien, pero primero tendrá que estudiar él cómo ganarse su confianza.',
                'price' => 100000,
                'release_date' => '2001-12-21',
                'cover' => 'somosQuintillizas02.jpg',
                'cover_description' => "Tapa del volumen 2 de Somos Quintillizas",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'serie_fk' => 2,
                'title' => 'Gotoubun no Hanayome 03',
                'en_alternative_title' => 'The Quintessential Quintuplets 03',
                'es_alternative_title' => 'Somos Quintillizas 03',
                'synopsis' => 'Fuutarou Uesugi es un estudiante de segundo año de preparatoria/instituto cuya familia siempre ha sido muy pobre. Un día recibe una suculenta oferta de trabajo como tutor a medio tiempo... ¡pero sus estudiantes resultan ser unas chicas de su propia clase! Para complicar más las cosas, son quintillizas... Las cinco hermanas son todas muy atractivas, pero no es lo único que tienen en común: todas odian estudiar y sus calificaciones siempre están al límite de la catástrofe. Tendrá que conseguir que las cinco estudien, pero primero tendrá que estudiar él cómo ganarse su confianza.',
                'price' => 100000,
                'release_date' => '2001-12-21',
                'cover' => 'somosQuintillizas03.jpg',
                'cover_description' => "Tapa del volumen 3 de Somos Quintillizas",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'serie_fk' => 2,
                'title' => 'Gotoubun no Hanayome 04',
                'en_alternative_title' => 'The Quintessential Quintuplets 04',
                'es_alternative_title' => 'Somos Quintillizas 04',
                'synopsis' => 'Fuutarou Uesugi es un estudiante de segundo año de preparatoria/instituto cuya familia siempre ha sido muy pobre. Un día recibe una suculenta oferta de trabajo como tutor a medio tiempo... ¡pero sus estudiantes resultan ser unas chicas de su propia clase! Para complicar más las cosas, son quintillizas... Las cinco hermanas son todas muy atractivas, pero no es lo único que tienen en común: todas odian estudiar y sus calificaciones siempre están al límite de la catástrofe. Tendrá que conseguir que las cinco estudien, pero primero tendrá que estudiar él cómo ganarse su confianza.',
                'price' => 100000,
                'release_date' => '2001-12-21',
                'cover' => 'somosQuintillizas04.jpg',
                'cover_description' => "Tapa del volumen 4 de Somos Quintillizas",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'serie_fk' => 3,
                'title' => 'Great Teacher Onizuka | GTO 01',
                'en_alternative_title' => 'Great Teacher Onizuka 01',
                'es_alternative_title' => 'GTO 01',
                'synopsis' => 'Eikichi Onizuka en su juventud era un pandillero, pero ahora sólo intenta conseguir que alguna mujer caiga rendida a sus pies. Después de una accidentada cita con una chica, descubre que siendo profe puede lograr que caigan rendidas a sus pies. Así se dispone a conseguir el título de profesor y buscar trabajo.',
                'price' => 120000,
                'release_date' => '2001-12-21',
                'cover' => 'gto01.jpg',
                'cover_description' => "Tapa del volumen 1 de Great Teacher Onizuka",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'serie_fk' => 3,
                'title' => 'Great Teacher Onizuka | GTO 02',
                'en_alternative_title' => 'Great Teacher Onizuka 02',
                'es_alternative_title' => 'GTO 02',
                'synopsis' => 'Eikichi Onizuka en su juventud era un pandillero, pero ahora sólo intenta conseguir que alguna mujer caiga rendida a sus pies. Después de una accidentada cita con una chica, descubre que siendo profe puede lograr que caigan rendidas a sus pies. Así se dispone a conseguir el título de profesor y buscar trabajo.',
                'price' => 120000,
                'release_date' => '2001-12-21',
                'cover' => 'gto02.jpg',
                'cover_description' => "Tapa del volumen 2 de Great Teacher Onizuka",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'serie_fk' => 3,
                'title' => 'Great Teacher Onizuka | GTO 03',
                'en_alternative_title' => 'Great Teacher Onizuka 03',
                'es_alternative_title' => 'GTO 03',
                'synopsis' => 'Eikichi Onizuka en su juventud era un pandillero, pero ahora sólo intenta conseguir que alguna mujer caiga rendida a sus pies. Después de una accidentada cita con una chica, descubre que siendo profe puede lograr que caigan rendidas a sus pies. Así se dispone a conseguir el título de profesor y buscar trabajo.',
                'price' => 120000,
                'release_date' => '2001-12-21',
                'cover' => 'gto03.jpg',
                'cover_description' => "Tapa del volumen 3 de Great Teacher Onizuka",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'serie_fk' => 3,
                'title' => 'Great Teacher Onizuka | GTO 04',
                'en_alternative_title' => 'Great Teacher Onizuka 04',
                'es_alternative_title' => 'GTO 04',
                'synopsis' => 'La suerte parece sonreírle cuando encuentra trabajo en un colegio privado, aunque lo que no sabe es que sus antecesores en el curso que le toca terminaron uno peor que el otro. Su dedicación para convertirse en el mejor profe y el odio a los sistemas de enseñanza tradicionales se verán puestos a prueba, usando métodos poco ortodoxos, algo ilegales y muy locos.',
                'price' => 120000,
                'release_date' => '2001-12-21',
                'cover' => 'gto04.jpg',
                'cover_description' => "Tapa del volumen 4 de Great Teacher Onizuka",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'serie_fk' => 4,
                'title' => 'Spy x Family 01',
                'en_alternative_title' => 'Spy x Family 01',
                'es_alternative_title' => 'Spy x Family 01',
                'synopsis' => 'Los países de Westalis y Ostania libran desde hace años una guerra fría donde el espionaje y los asesinatos son moneda corriente. El inigualable espía conocido como "Twilight" es el mejor agente de Westalis que tiene por objetivo encargarse del poderoso Donovan Desmond. El problema es que Desmond es un ermitaño antisocial cuyas únicas apariciones públicas son en los actos escolares de su hijo. Twilight deberá acercarse al objetivo lo suficiente como para desbaratar su agenda secreta. Para ello, sólo deberá simular que es un hombre de familia... con el pequeño detalle de que sólo tiene 7 días para conseguir la familia ideal.',
                'price' => 115000,
                'release_date' => '2001-12-21',
                'cover' => 'spyxfamily01.jpg',
                'cover_description' => "Tapa del volumen 1 de Spy x Family",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'serie_fk' => 4,
                'title' => 'Spy x Family 02',
                'en_alternative_title' => 'Spy x Family 02',
                'es_alternative_title' => 'Spy x Family 02',
                'synopsis' => 'Los países de Westalis y Ostania libran desde hace años una guerra fría donde el espionaje y los asesinatos son moneda corriente. El inigualable espía conocido como "Twilight" es el mejor agente de Westalis que tiene por objetivo encargarse del poderoso Donovan Desmond. El problema es que Desmond es un ermitaño antisocial cuyas únicas apariciones públicas son en los actos escolares de su hijo. Twilight deberá acercarse al objetivo lo suficiente como para desbaratar su agenda secreta. Para ello, sólo deberá simular que es un hombre de familia... con el pequeño detalle de que sólo tiene 7 días para conseguir la familia ideal.',
                'price' => 115000,
                'release_date' => '2001-12-21',
                'cover' => 'spyxfamily02.jpg',
                'cover_description' => "Tapa del volumen 2 de Spy x Family",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'serie_fk' => 4,
                'title' => 'Spy x Family 03',
                'en_alternative_title' => 'Spy x Family 03',
                'es_alternative_title' => 'Spy x Family 03',
                'synopsis' => 'Los países de Westalis y Ostania libran desde hace años una guerra fría donde el espionaje y los asesinatos son moneda corriente. El inigualable espía conocido como "Twilight" es el mejor agente de Westalis que tiene por objetivo encargarse del poderoso Donovan Desmond. El problema es que Desmond es un ermitaño antisocial cuyas únicas apariciones públicas son en los actos escolares de su hijo. Twilight deberá acercarse al objetivo lo suficiente como para desbaratar su agenda secreta. Para ello, sólo deberá simular que es un hombre de familia... con el pequeño detalle de que sólo tiene 7 días para conseguir la familia ideal.',
                'price' => 115000,
                'release_date' => '2001-12-21',
                'cover' => 'spyxfamily03.jpg',
                'cover_description' => "Tapa del volumen 3 de Spy x Family",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'serie_fk' => 4,
                'title' => 'Spy x Family 04',
                'en_alternative_title' => 'Spy x Family 04',
                'es_alternative_title' => 'Spy x Family 04',
                'synopsis' => 'Los países de Westalis y Ostania libran desde hace años una guerra fría donde el espionaje y los asesinatos son moneda corriente. El inigualable espía conocido como "Twilight" es el mejor agente de Westalis que tiene por objetivo encargarse del poderoso Donovan Desmond. El problema es que Desmond es un ermitaño antisocial cuyas únicas apariciones públicas son en los actos escolares de su hijo. Twilight deberá acercarse al objetivo lo suficiente como para desbaratar su agenda secreta. Para ello, sólo deberá simular que es un hombre de familia... con el pequeño detalle de que sólo tiene 7 días para conseguir la familia ideal.',
                'price' => 115000,
                'release_date' => '2001-12-21',
                'cover' => 'spyxfamily04.jpg',
                'cover_description' => "Tapa del volumen 4 de Spy x Family",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
